language: node_js
node_js:
- 12.10.0
cache: npm

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build 
  on:
    branch: main
  